version: "3.8"
services:
  web:
    container_name: backend
    build:
      context: ././
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: bash -c 'cd mobi_market; python manage.py collectstatic --no-input; python manage.py migrate; gunicorn mobi_market.wsgi:application -w 4 -b 0.0.0.0:8000;'
    volumes:
      - .:/mobi_market
    env_file:
      - .env
