# Generated by Django 5.0 on 2023-12-27 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CardProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("price", models.PositiveIntegerField()),
                ("photo", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("long_description", models.TextField(blank=True, null=True)),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="liked_card_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
