# Generated by Django 4.2.2 on 2023-12-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_create_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="")),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("birth_date", models.DateField(blank=True)),
            ],
        ),
    ]
