# Generated by Django 5.0 on 2023-12-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_create_field_code_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='code_activation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
